SELECT * FROM  TEST_MEMBER;

--INSERT INTO TEST_MEMBER

--UPDATE TEST_MEMBER SET

--DELETE  FROM  TEST_MEMBER

INSERT INTO TEST_MEMBER VALUES(10,'남윤주',sysdate);

INSERT INTO TEST_MEMBER VALUES(22,'이승환','1994-02-21');


INSERT INTO TEST_MEMBER VALUES('','이예지',''); --비어있는 ''를 INSERT하면 NULL 값 처리

--INSERT INTO TEST_MEMBER VALUES(10,'',sysdate);

INSERT INTO TEST_MEMBER VALUES(NULL,'문상현','2017-01-01');

--dBeaver 에서는 기본적으로 auto-commit 수행 

